/*
AUTOR:DIEGO SILVA
DATA:24/04/2020
DESCRIÇÃO:SCRIPT PARA CRIAR PROCEDURE PARA ATUALIZAR BOLETOS PAGOS
*/

CREATE OR REPLACE PROCEDURE ATUALIZAPAGAMENTO(
  p_MATRICULA IN VARCHAR2,
  p_PARCELA IN NUMBER
)
IS
  v_ID number;
BEGIN
  SELECT ID INTO v_ID
  FROM ALUNO
  WHERE MATRICULA =p_MATRICULA;
  
  UPDATE BOLETOS
  SET BOLETO_PAGO = 'S'
  WHERE ALUNO_ID=v_ID AND
  NUMERO_BOLETO=p_PARCELA;
  
  COMMIT;
END;


COMMIT;
DELETE FROM VERSAO_SISTEMA;
INSERT INTO VERSAO_SISTEMA VALUES(1,0,0,10);
INSERT INTO SCRIPT_EXECUTADOS VALUES(1,0,0,10,SYSDATE);
COMMIT;